labels = [
    "Abu Dhabi (AUH)",
    "Agadir (AGA)",
    "Algiers (ALG)",
    "Almaty (ALA)",
    "Amman (AMM)",
    "Amsterdam (AMS)",
    "Antalya (AYT)",
    "Ashgabat (ASB)",
    "Astana (TSE)",
    "Athens (ATH)",
    "Auckland (AKL)",
    "Bahrein (BAH)",
    "Baku (GYD)",
    "Bangkok (BKK)",
    "Barcelona (BCN)",
    "Basel (BSL)",
    "Beijing (PEK)",
    "Beirut (BEY)",
    "Bergen (BGO)",
    "Biarritz (BIQ)",
    "Bordeaux (BOD)",
    "Boston (BOS)",
    "Cairo (CAI)",
    "Chicago (ORD)",
    "Copenhagen (CPH)",
    "Dar Es Salaam (DAR)",
    "Delhi (DEL)",
    "Direct City (DCI)",
    "Doha (DOH)",
    "Dubai (DXB)",
    "Eden City (EDN)",
    "Eden Elite City (EEI)",
    "Edinburgh (EDI)",
    "Frankfurt (FRA)",
    "Geneva (GVA)",
    "Helsinki (HEL)",
    "Hong Kong (HKG)",
    "Ibiza (IBZ)",
    "Istanbul (IST)",
    "Johannesburg (JNB)",
    "Kuwait (KWI)",
    "Lisbon (LIS)",
    "London (LHR)",
    "Longyearbyen (LYR)",
    "Los Angeles (LAX)",
    "Madrid (MAD)",
    "Malaga (AGP)",
    "Mallorca (PMI)",
    "Manchester (MAN)",
    "Marrakech (RAK)",
    "Miami (MIA)",
    "Milan (MXP)",
    "Montreal (YUL)",
    "Moscow (DME)",
    "Mumbai (BOM)",
    "Munich (MUC)",
    "Muscat (MCT)",
    "Nairobi (NBO)",
    "Naples (NAP)",
    "New York (JFK)",
    "Nuuk (GOH)",
    "Ocean Shores (OSO)",
    "Oran (ORN)",
    "Oslo (OSL)",
    "Palermo (PMO)",
    "Paris (CDG)",
    "Prague (PRG)",
    "Porto (OPO)",
    "Puerto Marabella (PMB)",
    "Reykjavik (KEF)",
    "Rome (FCO)",
    "St. Petersburg (LED)",
    "San Francisco (SFO)",
    "Sao Paulo (GRU)",
    "Shanghai (PVG)",
    "Singapore (SIN)",
    "Stockholm (ARN)",
    "Swiss Alpin (SAI)",
    "Sydney (SYD)",
    "Tel Aviv (TLV)",
    "Tenerife (TFS)",
    "Tbilisi (TBS)",
    "Tokyo (NRT)",
    "Tunis (TUN)",
    "Valencia (VLC)",
    "Vienna (VIE)",
    "Yerevan (EVN)",
    "Zurich (ZRH)",
    "Asghabat (ASB)",
    "Tibilisi (TBS)",
    "Hong Kond (HKG)",
    "Kuwait (KWI)",
    "Dar Es Salaarm (DAR)",
    "Cairo (CAI)",
    "Casablanca (CMN)"
]

airport_name_by_label = {
    "Abu Dhabi (AUH)": "Abu Dhabi",
    "Agadir (AGA)": "Agadir",
    "Algiers (ALG)": "Algiers",
    "Almaty (ALA)": "Almaty",
    "Amman (AMM)": "Amman",
    "Amsterdam (AMS)": "Amsterdam",
    "Antalya (AYT)": "Antalya",
    "Ashgabat (ASB)": "Ashgabat",
    "Astana (TSE)": "Astana",
    "Athens (ATH)": "Athens",
    "Auckland (AKL)": "Auckland",
    "Bahrein (BAH)": "Bahrein",
    "Baku (GYD)": "Baku",
    "Bangkok (BKK)": "Bangkok",
    "Barcelona (BCN)": "Barcelona",
    "Basel (BSL)": "Basel",
    "Beijing (PEK)": "Beijing",
    "Beirut (BEY)": "Beirut",
    "Bergen (BGO)": "Bergen",
    "Biarritz (BIQ)": "Biarritz",
    "Bordeaux (BOD)": "Bordeaux",
    "Boston (BOS)": "Boston",
    "Cairo (CAI)": "Cairo",
    "Chicago (ORD)": "Chicago",
    "Copenhagen (CPH)": "Copenhagen",
    "Dar Es Salaam (DAR)": "Dar Es Salaam",
    "Delhi (DEL)": "Delhi",
    "Direct City (DCI)": "Direct City",
    "Doha (DOH)": "Doha",
    "Dubai (DXB)": "Dubai",
    "Eden City (EDN)": "Eden City",
    "Eden Elite City (EEI)": "Eden Elite City",
    "Edinburgh (EDI)": "Edinburgh",
    "Frankfurt (FRA)": "Frankfurt",
    "Geneva (GVA)": "Geneva",
    "Helsinki (HEL)": "Helsinki",
    "Hong Kong (HKG)": "Hong Kong",
    "Ibiza (IBZ)": "Ibiza",
    "Istanbul (IST)": "Istanbul",
    "Johannesburg (JNB)": "Johannesburg",
    "Kuwait (KWI)": "Kuwait",
    "Lisbon (LIS)": "Lisbon",
    "London (LHR)": "London",
    "Longyearbyen (LYR)": "Longyearbyen",
    "Los Angeles (LAX)": "Los Angeles",
    "Madrid (MAD)": "Madrid",
    "Malaga (AGP)": "Malaga",
    "Mallorca (PMI)": "Mallorca",
    "Manchester (MAN)": "Manchester",
    "Marrakech (RAK)": "Marrakech",
    "Miami (MIA)": "Miami",
    "Milan (MXP)": "Milan",
    "Montreal (YUL)": "Montreal",
    "Moscow (DME)": "Moscow",
    "Mumbai (BOM)": "Mumbai",
    "Munich (MUC)": "Munich",
    "Muscat (MCT)": "Muscat",
    "Nairobi (NBO)": "Nairobi",
    "Naples (NAP)": "Naples",
    "New York (JFK)": "New York",
    "Nuuk (GOH)": "Nuuk",
    "Ocean Shores (OSO)": "Ocean Shores",
    "Oran (ORN)": "Oran",
    "Oslo (OSL)": "Oslo",
    "Palermo (PMO)": "Palermo",
    "Paris (CDG)": "Paris",
    "Prague (PRG)": "Prague",
    "Porto (OPO)": "Porto",
    "Puerto Marabella (PMB)": "Puerto Marabella",
    "Reykjavik (KEF)": "Reykjavik",
    "Rome (FCO)": "Rome",
    "St. Petersburg (LED)": "St. Petersburg",
    "San Francisco (SFO)": "San Francisco",
    "Sao Paulo (GRU)": "Sao Paulo",
    "Shanghai (PVG)": "Shanghai",
    "Singapore (SIN)": "Singapore",
    "Stockholm (ARN)": "Stockholm",
    "Swiss Alpin (SAI)": "Swiss Alpin",
    "Sydney (SYD)": "Sydney",
    "Tel Aviv (TLV)": "Tel Aviv",
    "Tenerife (TFS)": "Tenerife",
    "Tbilisi (TBS)": "Tbilisi",
    "Tokyo (NRT)": "Tokyo",
    "Tunis (TUN)": "Tunis",
    "Valencia (VLC)": "Valencia",
    "Vienna (VIE)": "Vienna",
    "Yerevan (EVN)": "Yerevan",
    "Zurich (ZRH)": "Zurich",
    "Asghabat (ASB)": "Asghabat",
    "Tibilisi (TBS)": "Tibilisi",
    "Hong Kond (HKG)": "Hong Kond",
    "Kuwait (KWI)": "Kuwait",
    "Dar Es Salaarm (DAR)": "Dar Es Salaarm",
    "Cairo (CAI)": "Cairo",
    "Casablanca (CMN)": "Casablanca"
}

airport_code_by_label = {
    "Abu Dhabi (AUH)": "AUH",
    "Agadir (AGA)": "AGA",
    "Algiers (ALG)": "ALG",
    "Almaty (ALA)": "ALA",
    "Amman (AMM)": "AMM",
    "Amsterdam (AMS)": "AMS",
    "Antalya (AYT)": "AYT",
    "Ashgabat (ASB)": "ASB",
    "Astana (TSE)": "TSE",
    "Athens (ATH)": "ATH",
    "Auckland (AKL)": "AKL",
    "Bahrein (BAH)": "BAH",
    "Baku (GYD)": "GYD",
    "Bangkok (BKK)": "BKK",
    "Barcelona (BCN)": "BCN",
    "Basel (BSL)": "BSL",
    "Beijing (PEK)": "PEK",
    "Beirut (BEY)": "BEY",
    "Bergen (BGO)": "BGO",
    "Biarritz (BIQ)": "BIQ",
    "Bordeaux (BOD)": "BOD",
    "Boston (BOS)": "BOS",
    "Cairo (CAI)": "CAI",
    "Chicago (ORD)": "ORD",
    "Copenhagen (CPH)": "CPH",
    "Dar Es Salaam (DAR)": "DAR",
    "Delhi (DEL)": "DEL",
    "Direct City (DCI)": "DCI",
    "Doha (DOH)": "DOH",
    "Dubai (DXB)": "DXB",
    "Eden City (EDN)": "EDN",
    "Eden Elite City (EEI)": "EEI",
    "Edinburgh (EDI)": "EDI",
    "Frankfurt (FRA)": "FRA",
    "Geneva (GVA)": "GVA",
    "Helsinki (HEL)": "HEL",
    "Hong Kong (HKG)": "HKG",
    "Ibiza (IBZ)": "IBZ",
    "Istanbul (IST)": "IST",
    "Johannesburg (JNB)": "JNB",
    "Kuwait (KWI)": "KWI",
    "Lisbon (LIS)": "LIS",
    "London (LHR)": "LHR",
    "Longyearbyen (LYR)": "LYR",
    "Los Angeles (LAX)": "LAX",
    "Madrid (MAD)": "MAD",
    "Malaga (AGP)": "AGP",
    "Mallorca (PMI)": "PMI",
    "Manchester (MAN)": "MAN",
    "Marrakech (RAK)": "RAK",
    "Miami (MIA)": "MIA",
    "Milan (MXP)": "MXP",
    "Montreal (YUL)": "YUL",
    "Moscow (DME)": "DME",
    "Mumbai (BOM)": "BOM",
    "Munich (MUC)": "MUC",
    "Muscat (MCT)": "MCT",
    "Nairobi (NBO)": "NBO",
    "Naples (NAP)": "NAP",
    "New York (JFK)": "JFK",
    "Nuuk (GOH)": "GOH",
    "Ocean Shores (OSO)": "OSO",
    "Oran (ORN)": "ORN",
    "Oslo (OSL)": "OSL",
    "Palermo (PMO)": "PMO",
    "Paris (CDG)": "CDG",
    "Prague (PRG)": "PRG",
    "Porto (OPO)": "OPO",
    "Puerto Marabella (PMB)": "PMB",
    "Reykjavik (KEF)": "KEF",
    "Rome (FCO)": "FCO",
    "St. Petersburg (LED)": "LED",
    "San Francisco (SFO)": "SFO",
    "Sao Paulo (GRU)": "GRU",
    "Shanghai (PVG)": "PVG",
    "Singapore (SIN)": "SIN",
    "Stockholm (ARN)": "ARN",
    "Swiss Alpin (SAI)": "SAI",
    "Sydney (SYD)": "SYD",
    "Tel Aviv (TLV)": "TLV",
    "Tenerife (TFS)": "TFS",
    "Tbilisi (TBS)": "TBS",
    "Tokyo (NRT)": "NRT",
    "Tunis (TUN)": "TUN",
    "Valencia (VLC)": "VLC",
    "Vienna (VIE)": "VIE",
    "Yerevan (EVN)": "EVN",
    "Zurich (ZRH)": "ZRH",
    "Asghabat (ASB)": "ASB",
    "Tibilisi (TBS)": "TBS",
    "Hong Kond (HKG)": "HKG",
    "Kuwait (KWI)": "KWI",
    "Dar Es Salaarm (DAR)": "DAR",
    "Cairo (CAI)": "CAI",
    "Casablanca (CMN)": "CMN"
}

airport_timezone_by_label = {
    "Abu Dhabi (AUH)": "4",
    "Agadir (AGA)": "0",
    "Algiers (ALG)": "1",
    "Almaty (ALA)": "5",
    "Amman (AMM)": "2",
    "Amsterdam (AMS)": "1",
    "Antalya (AYT)": "2",
    "Ashgabat (ASB)": "4",
    "Astana (TSE)": "5",
    "Athens (ATH)": "2",
    "Auckland (AKL)": "12",
    "Bahrein (BAH)": "3",
    "Baku (GYD)": "3",
    "Bangkok (BKK)": "6",
    "Barcelona (BCN)": "1",
    "Basel (BSL)": "1",
    "Beijing (PEK)": "8",
    "Beirut (BEY)": "3",
    "Bergen (BGO)": "1",
    "Biarritz (BIQ)": "1",
    "Bordeaux (BOD)": "1",
    "Boston (BOS)": "-5",
    "Cairo (CAI)": "-2",
    "Chicago (ORD)": "-6",
    "Copenhagen (CPH)": "1",
    "Dar Es Salaam (DAR)": "3",
    "Delhi (DEL)": "5.5",
    "Direct City (DCI)": "1",
    "Doha (DOH)": "3",
    "Dubai (DXB)": "4",
    "Eden City (EDN)": "-5",
    "Eden Elite City (EEI)": "0",
    "Edinburgh (EDI)": "0",
    "Frankfurt (FRA)": "1",
    "Geneva (GVA)": "1",
    "Helsinki (HEL)": "2",
    "Hong Kong (HKG)": "8",
    "Ibiza (IBZ)": "1",
    "Istanbul (IST)": "2",
    "Johannesburg (JNB)": "2",
    "Kuwait (KWI)": "3",
    "Lisbon (LIS)": "0",
    "London (LHR)": "0",
    "Longyearbyen (LYR)": "1",
    "Los Angeles (LAX)": "-8",
    "Madrid (MAD)": "1",
    "Malaga (AGP)": "1",
    "Mallorca (PMI)": "1",
    "Manchester (MAN)": "0",
    "Marrakech (RAK)": "0",
    "Miami (MIA)": "-5",
    "Milan (MXP)": "1",
    "Montreal (YUL)": "-5",
    "Moscow (DME)": "3",
    "Mumbai (BOM)": "5.5",
    "Munich (MUC)": "1",
    "Muscat (MCT)": "4",
    "Nairobi (NBO)": "3",
    "Naples (NAP)": "1",
    "New York (JFK)": "-5",
    "Nuuk (GOH)": "-2",
    "Ocean Shores (OSO)": "-5",
    "Oran (ORN)": "1",
    "Oslo (OSL)": "1",
    "Palermo (PMO)": "1",
    "Paris (CDG)": "1",
    "Prague (PRG)": "1",
    "Porto (OPO)": "0",
    "Puerto Marabella (PMB)": "1",
    "Reykjavik (KEF)": "0",
    "Rome (FCO)": "1",
    "St. Petersburg (LED)": "3",
    "San Francisco (SFO)": "-8",
    "Sao Paulo (GRU)": "-4",
    "Shanghai (PVG)": "8",
    "Singapore (SIN)": "8",
    "Stockholm (ARN)": "1",
    "Swiss Alpin (SAI)": "1",
    "Sydney (SYD)": "10",
    "Tel Aviv (TLV)": "2",
    "Tenerife (TFS)": "0",
    "Tbilisi (TBS)": "3",
    "Tokyo (NRT)": "9",
    "Tunis (TUN)": "1",
    "Valencia (VLC)": "1",
    "Vienna (VIE)": "1",
    "Yerevan (EVN)": "3",
    "Zurich (ZRH)": "1",
    "Asghabat (ASB)": "4",
    "Tibilisi (TBS)": "3",
    "Hong Kond (HKG)": "8",
    "Kuwait (KWI)": "1",
    "Dar Es Salaarm (DAR)": "3",
    "Cairo (CAI)": "2",
    "Casablanca (CMN)": "0"
}

connecting_points = {
    "PMB": 30,
    "DCI": 45,
    "EEI": 20,
    "SAI": 20
}

config = {
    "A319": {"F": 0, "C": 8, "E": 0, "Y": 36},
    "A32A": {"F": 0, "C": 8, "E": 0, "Y": 42},
    "A32N": {"F": 0, "C": 12, "E": 0, "Y": 42},
    "A32B": {"F": 0, "C": 16, "E": 0, "Y": 58},
    "A32L": {"F": 0, "C": 12, "E": 0, "Y": 58},
    "A333": {"F": 0, "C": 18, "E": 0, "Y": 56},
    "A343": {"F": 4, "C": 15, "E": 0, "Y": 49},
    "A342": {"F": 0, "C": 18, "E": 0, "Y": 56},
    "A359": {"F": 0, "C": 0, "E": 0, "Y": 0},
    "B77L": {"F": 8, "C": 34, "E": 18, "Y": 54},
    "B77W": {"F": 8, "C": 42, "E": 12, "Y": 90}
}
